# SMTP configuration
smtp:
  domain: my-domain-name.ch
  server: 127.0.0.1
  port: 25

# Minimum size of group is 3
group_size: 5

# The list of victims. One at a line
files:
  victim: D:\prank-campaign\list_of_victim.txt

# A file per message. The name of the file will be use as the email subject
folder:
  message: D:\prank-campaign\messages